// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZO2TGoRdHGY2K0ZH2qNkbEBkDCemgFmg',
    appId: '1:957652311085:web:3a82209644a4c5b5632ca4',
    messagingSenderId: '957652311085',
    projectId: 'tourandtravel-10683',
    authDomain: 'tourandtravel-10683.firebaseapp.com',
    storageBucket: 'tourandtravel-10683.appspot.com',
    measurementId: 'G-M4VWVVY4CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAEqsekbyDFhL7cne1bePt-38PDDVAN8I',
    appId: '1:957652311085:android:008bc39f6dcda15d632ca4',
    messagingSenderId: '957652311085',
    projectId: 'tourandtravel-10683',
    storageBucket: 'tourandtravel-10683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLIjGex6JbjzXB251c3bf-tZ_YdU8APho',
    appId: '1:957652311085:ios:aeed347b6ff1244a632ca4',
    messagingSenderId: '957652311085',
    projectId: 'tourandtravel-10683',
    storageBucket: 'tourandtravel-10683.appspot.com',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLIjGex6JbjzXB251c3bf-tZ_YdU8APho',
    appId: '1:957652311085:ios:aeed347b6ff1244a632ca4',
    messagingSenderId: '957652311085',
    projectId: 'tourandtravel-10683',
    storageBucket: 'tourandtravel-10683.appspot.com',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZO2TGoRdHGY2K0ZH2qNkbEBkDCemgFmg',
    appId: '1:957652311085:web:b4f9a500dea9a54c632ca4',
    messagingSenderId: '957652311085',
    projectId: 'tourandtravel-10683',
    authDomain: 'tourandtravel-10683.firebaseapp.com',
    storageBucket: 'tourandtravel-10683.appspot.com',
    measurementId: 'G-0C1875BQZV',
  );
}
